
stages:
  - test
  - report
  - upload

run_tests:
  stage: test
  script:
    - mvn clean test

generate_allure:
  stage: report
  script:
    - mvn allure:report

upload_results:
  stage: upload
  script:
    - mvn compile exec:java -Dexec.mainClass="com.example.zephyr.ZephyrUploader"
